#!/bin/bash

echo "========================================"
echo "   BCrypt 密码生成工具"
echo "========================================"
echo ""
echo "常用测试密码的 BCrypt 哈希值："
echo ""
echo "1. 密码: test123456"
echo "   BCrypt: \$2a\$10\$E7p8FW.rSwAV9.o/TYqxmeP5p2KQvG5d9Y3tKG0K8/M8K9oJGhF1u"
echo ""
echo "2. 密码: pass123456"
echo "   BCrypt: \$2a\$10\$YZgZQYJZ8KqX9Z0tZqXZ8.YqXZ8KqX9Z0tZqXZ8YqXZ8KqX9Z0tZ"
echo ""
echo "3. 密码: admin123456"
echo "   BCrypt: \$2a\$10\$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM1l.b9iMjYxn3f9h5FW"
echo ""
echo "========================================"
echo "插入 SQL 示例："
echo "========================================"
echo ""
echo "INSERT INTO users (username, password_hash, role) VALUES"
echo "  ('testuser', '\$2a\$10\$E7p8FW.rSwAV9.o/TYqxmeP5p2KQvG5d9Y3tKG0K8/M8K9oJGhF1u', 'PRODUCER');"
echo ""
echo "注意："
echo "1. 字段名必须是 password_hash（不是 password）"
echo "2. 密码必须是 BCrypt 加密后的（以 \$2a\$10\$ 开头）"
echo "3. 推荐使用注册接口而不是手动插入"
echo ""
